version: '3.1'

services:
  db:
    image: postgres:14.5
    restart: always
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
    environment:
      - "POSTGRES_USER=example"
      - "POSTGRES_PASSWORD=Pazzwerd0123"
    ports:
      - "5432:5432"
